# Docker image
# Build a Docker image to deploy, run, or push to a container registry.
# Add steps that use Docker Compose, tag images, push to a registry, run an image, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  buildConfiguration: 'Release'
  imageName: 'vehicletracker:$(Build.BuildId)'

# steps:
# - script: docker build -f src/EventStore.Middleware/Dockerfile -t $(imageName) .
# - script: docker build -f src/Vehicle.Service/Dockerfile -t $(imageName) .
#   displayName: 'docker build'

- script: |
    dotnet build src/VehicleTracker.sln --configuration $(buildConfiguration)
    dotnet test  src/VehicleTracker.sln --configuration $(buildConfiguration) --logger trx
    dotnet publish --configuration $(buildConfiguration) --output out
