version: '3.4'

services:
  vehicle:
    image: ${DOCKER_REGISTRY-}vehicle
    build:
      context: .
      dockerfile: Vehicle/Dockerfile


        
  database_sql:
    image: microsoft/mssql-server-windows-express:latest
    environment:
    - sa_password=Pass@word
    - ACCEPT_EULA=Y
    ports:
    - 5553:1433