version: '3.4'

services:
  eventstore:
    image: eventstore
    build:
      context: .
      dockerfile: EventStore.Middleware/Dockerfile
    environment:
    - db_connection=Server=database_sql;Database=event_sourcing;User Id=sa;Password=Pass@word
    depends_on:
    - database_sql

  database_sql:
    image: microsoft/mssql-server-linux:latest
    environment:
    - MSSQL_SA_PASSWORD=Pass@word
    - ACCEPT_EULA=Y
    - MSSQL_PID=Express
    ports:
    - 5553:1433