version: '3.4'
 
volumes:
  mongo_data:
  cassandra_data:

services:
  eventstore:
    image: eventstore
    build:
      context: .
      dockerfile: EventStore.Middleware/Dockerfile
    environment:
    - ASPNETCORE_ENVIRONMENT=Development
    - ES_CONNECTION=Server=database_sql;Database=event_sourcing;User Id=sa;Password=Pass@word
    depends_on:
    - database_sql
    ports:
    - 32770:80

  vehicle:
    image: vehicle
    build:
      context: .
      dockerfile: Vehicle.Service/Dockerfile
    environment:
    - ASPNETCORE_ENVIRONMENT=Development
    - ES_CONNECTION=Server=database_sql;Database=event_sourcing;User Id=sa;Password=Pass@word
    - DB_CONNECTION=Server=database_sql;Database=vehicle;User Id=sa;Password=Pass@word
    depends_on:
    - database_sql  
    - eventstore
    ports:
    - 32772:80

  database_sql:
    image: microsoft/mssql-server-linux:latest
    environment:
    - MSSQL_SA_PASSWORD=Pass@word
    - ACCEPT_EULA=Y
    - MSSQL_PID=Express
    ports:
    - 5553:1433